openapi: 3.0.0
info:
  title: Azure Sample
  description: Sample swagger file to test Azure imports
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/idsweb7/azuretemplate/1.0.0
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
